### ISSUE TITLE
Latest version is not the right version?

### ISSUE THREAD

**Issue by DerTyp7214** [bostrot/PowerToysRunPluginWinget#10]
[OhMyPosh](https://github.com/microsoft/winget-pkgs/tree/master/manifests/j/JanDeDobbeleer/OhMyPosh) latest version is 17.0.0 but the plugin says 9.5.0. Firefox is another example.

Maybe a option to choose the version would be nice.

**Comment by bostrot** [comment]
Good point but it installs the latest version anyways. Even if it shows a different one.

**Comment by bostrot** [comment]
Should be fixed now. At least for normal version strings.

**Comment by DerTyp7214** [comment]
works, thanks.
