### ISSUE TITLE
Installation instructions 

### ISSUE THREAD

**Issue by kdpuvvadi** [bostrot/PowerToysRunPluginWinget#14]
Instructions for installation states the path `C:\Program Files\PowerToys\modules\launcher\Plugins` but it's for the system install.

By default powertoys installs as a user and the path is `$ENV:LOCALAPPDATA\PowerToys\modules\launcher\Plugins`.

**Comment by The-Running-Dev** [comment]
The proper path is now

C:\Users\%YourUsername%\AppData\Local\Microsoft\PowerToys\PowerToys Run\Plugins\WinGet

**Comment by bostrot** [comment]
I just updated the README.
