### ISSUE TITLE
Plugin stopped working after PowerToys v0.72.0

### ISSUE THREAD

**Issue by tim-rue** [bostrot/PowerToysRunPluginWinget#16]
I installed the plugin a few weeks ago and it works fine. I recently updated PowerToys and it doesn't work anymore. I reinstalled, restarted etc. but it still doesn't work.

**Comment by bostrot** [comment]
Apparently the PowerToys Run Plugin directory was changed after the last release. The new location is `C:\Program Files\PowerToys\RunPlugins` or if you have a user install then `LOCATION\PowerToys\RunPlugins`.
------- Original Message -------
