### ISSUE TITLE
Files in the release zip archive

### ISSUE THREAD

**Issue by hlaueriksson** [bostrot/PowerToysRunPluginWinget#2]
Some files in the release zip archive, `Winget.zip` `v1.1.0`, is missing or unnecessary.

Missing:

- `Images\Winget.dark.png`
- `Images\Winget.light.png`

Unnecessary:

- `PowerToys.Settings.UI.Lib.dll`
- `PowerToys.Settings.UI.Lib.pdb`
- `PowerToys.Interop.dll`
- `PowerToys.Interop.pdb`
- `PowerToys.Common.UI.dll`
- `PowerToys.Common.UI.pdb`
- `PowerToys.ManagedCommon.dll`
- `PowerToys.ManagedCommon.pdb`
- `PowerToys.ManagedTelemetry.dll`
- `PowerToys.ManagedTelemetry.pdb`
- `Ijwhost.dll`
- `backup_restore_settings.json`

**Comment by bostrot** [comment]
This should do the trick: https://github.com/bostrot/PowerToysRunPluginWinget/releases/tag/v1.1.1
Thanks for reporting :)

**Comment by hlaueriksson** [comment]
Awesome!

It would be nice if the content in the zip file was in a `Winget` folder, like in the previous version.
That would make it easier to extract the plugin to the appropriate location.

**Comment by bostrot** [comment]
Here we go :)

https://github.com/bostrot/PowerToysRunPluginWinget/releases/tag/v1.1.2
