### ISSUE TITLE
Issue Adding Plugin to `PowerToys` Installed via Microsoft Store

### ISSUE THREAD

**Issue by DhananjayPorwal** [bostrot/PowerToysRunPluginWinget#20]
I recently installed the PowerToys app from the Microsoft Store. However, upon attempting to add a plugin to the app's directory (`C:\Users\%username%\AppData\Local\Microsoft\PowerToys\PowerToys Run\Plugins`), I encountered the following error:

![Error Image](https://github.com/bostrot/PowerToysRunPluginWinget/assets/51775507/edbba470-48b4-4016-a2ba-59866dc0edd5)

The plugin functions correctly with the installer version but encounters issues when used with the Microsoft Store app.

Could you provide guidance or a workaround to enable the plugin's functionality with the Microsoft Store version of PowerToys?

**Comment by VonSchnitzel** [comment]
Receiving the similar error here, but copied the plugin to the "C:\Program Files\PowerToys\RunPlugins" path. Error just states failed to load plugin:Winget and it'll be disabled.

Using PowerToys Store version (0.76.2), installed via winget,

**Comment by DhananjayPorwal** [comment]
The reason behind this is that when `PowerToys` are installed via Winget or the Microsoft Store, they're placed in `C:\Program Files\WindowsApps`. This presents a common issue for all users regardless of version.
The primary challenge lies in the fact that this location restricts users from accessing or modifying the folder without manual intervention.

> Receiving the similar error here, but copied the plugin to the "C:\Program Files\PowerToys\RunPlugins" path. Error just states failed to load plugin:Winget and it'll be disabled.
> 
> Using PowerToys Store version (0.76.2), installed via winget,

**Comment by bostrot** [comment]
Can you check the README's new path/installation instructions and see if they work? I just updated it.

**Comment by DhananjayPorwal** [comment]
> Can you check the README's new path/installation instructions and see if they work? I just updated it.

Thank you for the prompt update! I followed the new path/installation instructions provided in the `README`, and I'm happy to confirm that the plugin is now functioning perfectly with the Microsoft Store version of `PowerToys`.

![image](https://github.com/bostrot/PowerToysRunPluginWinget/assets/51775507/6dbd88ae-ca94-476c-b7a6-48980d113f14)
