### ISSUE TITLE
Failed to load plugin: winget

### ISSUE THREAD

**Issue by plhrtr** [bostrot/PowerToysRunPluginWinget#22]
![ErrorMessage](https://github.com/bostrot/PowerToysRunPluginWinget/assets/63469583/1704f00c-a1ef-4213-a274-c152c5a9c7c2)
Hi, 
This issue was mentioned a few times and i really tried to make it work. 
But the error accours everytime, i tried putting the plugin at the location you mentioned in the Readme and also the location that is mentioned here [PowerToysDoc](https://github.com/microsoft/PowerToys/blob/main/doc/thirdPartyRunPlugins.md) 
I also tried installing PowerToys in all possible ways (winget, msstore, .exe from Github) 
I think this is a really handy plugin and would really like it to work. 
I also attached my log if that helps. [2024-01-05.txt](https://github.com/bostrot/PowerToysRunPluginWinget/files/13844318/2024-01-05.txt)

Any suggestions?

Thank you in advance!

Paul

**Comment by bostrot** [comment]
Have you tried this with v1.2.3? Also, the PowerToys plugin folder changes (see README.md)

**Comment by plhrtr** [comment]
I'm using version 1.2.3 
And tried putting it in %LOCALAPPDATE%\PowerToys\RunPlugins and %LOCALAPPDATE%\PowerToys\PowerToys Run\Plugins 

In both cases the same result.

**Comment by plhrtr** [comment]
When I put another Plugin in either of those folder (only tested with PowerTranslator Plugin) the error doesn't accure and the plugin works.

**Comment by bostrot** [comment]
Try %LOCALAPPDATA%\PowerToys\RunPlugins

**Comment by plhrtr** [comment]
> I'm using version 1.2.3 
> And tried putting it in %LOCALAPPDATE%\PowerToys\RunPlugins and %LOCALAPPDATE%\PowerToys\PowerToys Run\Plugins 
> 
> In both cases the same result. 

I already tried, same result (misspelled the directory, should be of course DATA)

**Comment by zeyus** [comment]
> > I'm using version 1.2.3
> > And tried putting it in %LOCALAPPDATE%\PowerToys\RunPlugins and %LOCALAPPDATE%\PowerToys\PowerToys Run\Plugins
> > In both cases the same result.
> 
> I already tried, same result (misspelled the directory, should be of course DATA)

My plugin location is:

`%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Plugins\Winget`

I'm using `PowerToys (Preview) v0.76.2` and `PowerToysRunPluginWinget 1.2.3` and there are no issues with that error. I had it on the previous version but no longer.

Maybe you have the plugin installed in multiple locations and that's causing the issue?

**Comment by plhrtr** [comment]
Maybe, 
But I looked everywhere and removed it, after putting it in the location you mentioned, still the same problem. 

But if it works for you, the problem is probably on my side, so I'm going to close this issue. And maybe give an update if I find a solution

Thanks regardless

**Comment by bostrot** [comment]
I actually had the problem with multiple plug-in locations before, so maybe reinstall power toys and check again?

**Comment by zeyus** [comment]
> Maybe, But I looked everywhere and removed it, after putting it in the location you mentioned, still the same problem.
> 
> But if it works for you, the problem is probably on my side, so I'm going to close this issue. And maybe give an update if I find a solution
> 
> Thanks regardless

If you're interested you can see which one it attempts to load at run-time by getting the DLLs:

https://learn.microsoft.com/en-us/sysinternals/downloads/listdlls

That can show you which ones are loaded and where for a particular process ID. Then you'll know for sure which version/ plugin path it's trying to use. (Process explorer can do a similar thing with showing all open file hooks)


e.g.

![image](https://github.com/bostrot/PowerToysRunPluginWinget/assets/75656/c74003bf-a9f0-4691-b9b1-df76d24f2372)

```powershell
C:\tools\ListDLLs\Listdlls64.exe 16048 | findstr "Winget"
```

<img width="1078" alt="image" src="https://github.com/bostrot/PowerToysRunPluginWinget/assets/75656/0719b48b-8362-4cb1-9ab0-0d6958fabe26">

**Comment by plhrtr** [comment]
> > Maybe, But I looked everywhere and removed it, after putting it in the location you mentioned, still the same problem.
> > But if it works for you, the problem is probably on my side, so I'm going to close this issue. And maybe give an update if I find a solution
> > Thanks regardless
> 
> If you're interested you can see which one it attempts to load at run-time by getting the DLLs:
> 
> https://learn.microsoft.com/en-us/sysinternals/downloads/listdlls
> 
> That can show you which ones are loaded and where for a particular process ID. Then you'll know for sure which version/ plugin path it's trying to use. (Process explorer can do a similar thing with showing all open file hooks)
> 
> e.g.
> 
> ![image](https://private-user-images.githubusercontent.com/75656/294859756-c74003bf-a9f0-4691-b9b1-df76d24f2372.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMDQ4OTIsIm5iZiI6MTcwNTAwNDU5MiwicGF0aCI6Ii83NTY1Ni8yOTQ4NTk3NTYtYzc0MDAzYmYtYTlmMC00NjkxLWI5YjEtZGY3NmQyNGYyMzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDIwMjMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5YWRkMjM3OTI4MzBhZDMxZjYzMGJiYjBjYzQ4ZTZlZWE5ODdkZmIzNWY3YmYxODU4Nzk3Y2M4YTZkYmUwYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w1y9wIrdpX6WpkUFKONTWYctQNYSS8GawKhfZenGTUQ)
> 
> ```powershell
> C:\tools\ListDLLs\Listdlls64.exe 16048 | findstr "Winget"
> ```
> 
> <img alt="image" width="1078" src="https://private-user-images.githubusercontent.com/75656/294859993-0719b48b-8362-4cb1-9ab0-0d6958fabe26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMDQ4OTIsIm5iZiI6MTcwNTAwNDU5MiwicGF0aCI6Ii83NTY1Ni8yOTQ4NTk5OTMtMDcxOWI0OGItODM2Mi00Y2IxLTlhYjAtMGQ2OTU4ZmFiZTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDIwMjMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZTRmYzEwNzdmZTNmNWVkODc3ZTBjMWZjY2YzODAwZjA3ODYxMWMwNTM3ZjdjYzVjOGEwZTYyYzExZTNjMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4IQM6udAeWtEjRhyjZSk9GH4HbLnKOIeHxH89plm3aE">

Since the new Update 0.77.0 the plugins works for me (maybe the update fixed the issue you mentioned, i haven´t found the time to look into it, but it works now, thanks regardless)

Thank`s guys for the help!
