### ISSUE TITLE
Fail to initialize plugins error

### ISSUE THREAD

**Issue by Lawrence-of-AnKing** [bostrot/PowerToysRunPluginWinget#28]
Install and restart the PC, it shows `Fail to initialize plugins`.

I try to uninstall all plugins, noting, will install Winget plugin only, it shows.

PowerToys 0.79 WingetPlugin 1.2.3

BTW: Is there any plan about uninstall command by PowerToyRun?

**Comment by leotsaiCode** [comment]
same problem and alt+space won't work after install this plugin, else plugin work fine with alt+space shortcut

**Comment by JotaRata** [comment]
This issue is still happening

**Comment by JotaRata** [comment]
Update to my previous comment: The bug appears to trigger when you start powertoys or boot your computer without an active internet connection (i.e. sign in to network)
