### ISSUE TITLE
Integration with winget.run/Live package querying

### ISSUE THREAD

**Issue by snargledorf** [bostrot/PowerToysRunPluginWinget#8]
It would be awesome to see this integrated with https://winget.run/ to be able to pull an up to date list of packages.
Either that or implement a similar polling of the winget package commits like how winget.run does.

https://github.com/winget-run/api/blob/master/src/server/ghService/update/updatePackageUtil.ts

**Comment by bostrot** [comment]
Not sure what they do differently. The package list here is updated daily from the winget-pkgs repository.
Could you elaborate?

**Comment by snargledorf** [comment]
Ah I see now. I missed that there is a local script downloading the latest manifests!

Feel free to disregard 😊

**Comment by bostrot** [comment]
Yes, I put it in an extra branch for now, so the main branch doesn't get nuked by commits with github actions from the [updater.ps1](https://github.com/bostrot/PowerToysRunPluginWinget/blob/main/updater.ps1) ([nightly-packages](https://github.com/bostrot/PowerToysRunPluginWinget/tree/nightly-packages)) 😊

Although I must say winget.run seems like an interesting project. Thanks for sharing!
